### ISSUE TITLE
Errors on npm install

### ISSUE THREAD

**Issue by Brramble** [tedle/uitabot#15]
Hi I've installed a fresh VM and followed your commands exactly from the documentation, there seems to be some NPM errors and it fails for version related things. Can you please let me know your exact versions that work for you?

Thanks a lot

**Comment by tedle** [comment]
The build looks to be working with Node.js v10.19.0 and npm v6.14.4, which are the defaults in Ubuntu 20.04. Using a newer version of node does break things, but getting all of the dependencies to play nice on both versions is not looking easy. Will probably leave things as is for now. Hopefully this helps.
